### PR TITLE
link/redirect change

### PR DESCRIPTION
**Pull request by abhi5456**

### CODE REVIEW

**Comment by polymorpher** [comment]
Needs to update package.json and lock files. Why are out-of-context links (all., and footer link) do not have target=_blank?

**Comment by abhi5456** [comment]
they dont have the target=_blank, so that they open in the same tab

**Comment by abhi5456** [comment]
i could have the code say target=_self, so that it is defined

**Comment by polymorpher** [comment]
Yes, I wanted to ask, why should out-of-context links be opened in the same tab?

**Comment by abhi5456** [comment]
stephen wants them to be opened in the same tab, instead of a new tab

**Comment by polymorpher** [comment]
_self is default value, you don't need to specify in code. Is there a good reason to have links that are not a subdomain of 1.country opened in the same tab? It is unconventional. Separately, in the root landing page (1.country), the link (all.1.country) appears in the early portion of the text. If the link is opened in the same tab, the user's reading will be disrupted and they still lose context after they managed to come back using back button.

**Comment by polymorpher** [comment]
`.yarn-integrity` should be ignored. It is dependent on platform and local settings. `package-lock.json` should be removed. It is managed by npm, not yarn

**Comment by abhi5456** [comment]
i think we can make all.1.country go to another page, but I believe it is better to leave next/prev open in the same tab like stephen said

**Review by polymorpher — APPROVED** [review]
Fixed and merged

**Pull request merged**
